import type { LearningOpportunity } from "../data/opportunities";

export type BotContext = { ids?: string[]; age?: number; organizer?: string; field?: string; kind?: string; mode?: string; free?: boolean };
export const normalize = (text: string) => text.toLowerCase().replace(/[’']/g, "").replace(/[أإآ]/g, "ا").replace(/ى/g, "ي").replace(/ة/g, "ه").replace(/[\u064B-\u065Fـ]/g, "").replace(/[٠-٩]/g, x => String("٠١٢٣٤٥٦٧٨٩".indexOf(x))).replace(/[^\p{L}\p{N}\s]/gu, " ").replace(/\s+/g, " ").trim();

export const botGroups = [
  { id: "registration", ar: "التسجيل والحساب", en: "Registration & accounts" },
  { id: "eligibility", ar: "العمر والشروط", en: "Age & eligibility" },
  { id: "fees", ar: "الرسوم والدفع", en: "Fees & payments" },
  { id: "attendance", ar: "الحضور والشهادات", en: "Attendance & certificates" },
  { id: "directory", ar: "البحث والمصادر", en: "Search & sources" },
  { id: "help", ar: "المساعدة والمشاكل", en: "Help & troubleshooting" },
];
type Faq = { id: string; group: string; ar: string; en: string; answerAr: string; answerEn: string; aliases?: RegExp };
const faq = (id: string, group: string, ar: string, en: string, answerAr: string, answerEn: string, aliases?: RegExp): Faq => ({ id, group, ar, en, answerAr, answerEn, aliases });
export const botFaqs: Faq[] = [
  faq("register", "registration", "شلون أسجل في دورة؟", "How do I register for a course?", "افتح بطاقة الدورة ثم «موقع الجهة للتسجيل». كمل الطلب في الموقع الرسمي، وراجع شروط الجهة قبل الإرسال.", "Open a course card and choose Official registration. Complete the application on the official website and review the organizer’s requirements.", /شلون.*(?:اسجل|التسجيل)|كيف.*اسجل|طريقه التسجيل|how.*register/),
  faq("account", "registration", "أحتاج حساب في مرصاد؟", "Do I need a Mirsad account?", "تصفح الدورات واستخدام البوت ما يحتاج حساب في مرصاد. الجهة المنظمة ممكن تطلب حسابًا في موقعها للتسجيل.", "Browsing courses and using this bot needs no Mirsad account. The organizer may require an account on its own site.", /احتاج حساب|لازم حساب|حساب في مرصاد|need.*account/),
  faq("confirmation", "registration", "شلون أتأكد أن تسجيلي تم؟", "How do I confirm my registration?", "شوف رسالة التأكيد أو حالة الطلب في حسابك لدى الجهة. مرصاد ما يقدر يشوف طلبك أو يؤكد قبوله؛ تواصل مع الجهة إذا ما وصلك تأكيد.", "Check the organizer’s confirmation message or your application status there. Mirsad cannot view or confirm your application.", /تسجيلي تم|تاكيد التسجيل|وصل.*تسجيل|confirm.*registration/),
  faq("documents", "registration", "شنو المستندات المطلوبة؟", "Which documents are required?", "المستندات تختلف حسب البرنامج. صفحة التسجيل الرسمية تبيّن المطلوب؛ لا ترسل بطاقتك المدنية أو مستنداتك في البوت.", "Required documents vary by program. Check the official application page; do not send ID documents to this bot.", /مستند|اوراق مطلوب|documents/),
  faq("edit", "registration", "أقدر أعدّل بيانات التسجيل؟", "Can I edit my application?", "التعديل يكون من حسابك في موقع الجهة إن كان متاحًا، أو بالتواصل معها. مرصاد ما يغيّر طلبات التسجيل.", "Edit through your account on the organizer’s site if available, or contact them. Mirsad cannot change applications.", /اعدل.*تسجيل|تعديل.*طلب|edit.*application/),
  faq("others", "registration", "أقدر أسجل لشخص ثاني؟", "Can I register someone else?", "راجع شروط الجهة بخصوص تسجيل شخص آخر أو ولي الأمر، واستخدم بيانات المتقدم الصحيحة وبموافقته.", "Check the organizer’s rules for registering another person or acting as a guardian, and use the applicant’s correct details with consent."),
  faq("seats", "registration", "هل التسجيل يضمن لي مقعد؟", "Does applying guarantee a seat?", "لا، وجود رابط التقديم ما يضمن مقعد أو قبول. الجهة تؤكد التوفر والقبول بعد مراجعة طلبك.", "No. An application link does not guarantee a seat or acceptance. The organizer confirms availability and admission.", /مقعد|مقاعد|مضمون|seats|guarantee/),
  faq("age", "eligibility", "شلون أعرف الدورة تناسب عمري؟", "How do I check the age range?", "شوف العمر في بطاقة الدورة، أو اكتب «عمري 16 وأبي دورات». مطابقة العمر وحدها ما تؤكد الأهلية؛ راجع بقية شروط الجهة.", "Check the age range on the card, or say “I’m 16 and want courses.” Matching the age alone does not confirm eligibility; check other requirements."),
  faq("unknown-age", "eligibility", "ليش العمر مكتوب غير معلن؟", "Why is the age range not announced?", "الجهة ما نشرت عمرًا محددًا في البيانات المتوفرة. ما نعتبرها مناسبة لكل الأعمار، وتختفي من البحث المحدد بالعمر إلى أن يتوفر شرط موثّق.", "The available announcement has no specific age range. We do not assume all ages qualify, and exclude it from age-filtered searches.", /العمر.*غير معلن|age.*not announced/),
  faq("children", "eligibility", "في دورات للأطفال؟", "Are there courses for children?", "اكتب عمر الطفل ومجاله، مثل «عمره 9 ويحب التقنية». البوت يبحث في الأعمار المعلنة؛ تأكد من شروط ولي الأمر لدى الجهة.", "Tell me the child’s age and interest, such as “age 9 technology.” I use published ages; check guardian requirements with the organizer.", /للاطفال|للصغار|for children|for kids/),
  faq("nationality", "eligibility", "الدورات للكويتيين فقط؟", "Are courses only for Kuwaiti nationals?", "شرط الجنسية يختلف بين البرامج. راجع وصف الدورة وصفحة الجهة؛ إذا الشرط مو مذكور ما أقدر أؤكد الأهلية.", "Nationality requirements vary. Check the course description and official page; an unstated requirement cannot be confirmed.", /كويتيين|كويتي فقط|غير كويتي|مقيم|nationality|nationals/),
  faq("experience", "eligibility", "لازم عندي خبرة سابقة؟", "Do I need previous experience?", "يعتمد على الدورة. دور على المتطلبات السابقة في وصفها وصفحة التسجيل، واسأل الجهة إذا ما كانت واضحة.", "It depends on the course. Check prerequisites in its description and application page, or ask the organizer.", /خبره سابقه|متطلبات سابقه|prerequisite|previous experience/),
  faq("beginners", "eligibility", "أنا مبتدئ، شنو أختار؟", "I’m a beginner. What should I choose?", "حدد المجال اللي تبيه وابحث عن وصف يذكر أنه للمبتدئين. اسم الدورة وحده ما يكفي لتحديد المستوى؛ راجع المتطلبات أو اسأل المنظم.", "Choose your field and look for an explicit beginner-level description. A title alone does not establish the level; check requirements with the organizer.", /مبتدي|مبتدئ|beginner/),
  faq("gender", "eligibility", "الدورات للبنات أو للشباب؟", "Are courses for women or men?", "الفئة المستهدفة يحددها المنظم. راجع الوصف الرسمي؛ ما نستنتج شرط الجنس من الصور أو اسم الدورة.", "The organizer specifies eligibility. Check the official description; we do not infer gender restrictions from images or titles.", /للبنات|للشباب|للنساء|للرجال|for women|for men/),
  faq("free", "fees", "هل كل الدورات مجانية؟", "Are all courses free?", "لا، الرسوم تختلف. «مجاني» يعني أن المجانية معلنة؛ «غير معلن» يعني ما عندنا سعر موثّق. اكتب «دورات مجانية» للبحث.", "No. “Free” means explicitly announced as free; “not announced” means no verified price. Search “free courses” for free listings."),
  faq("unknown-fees", "fees", "شنو يعني الرسوم غير معلنة؟", "What do unannounced fees mean?", "يعني الجهة ما وضحت الرسوم في المعلومات المتوفرة. مو معناته مجاني؛ تحقق من صفحة التسجيل قبل الدفع.", "The available information does not state the fee. It does not mean free; check the registration page.", /رسوم.*غير معلن|سعر.*غير معلن|unannounced fees/),
  faq("payment", "fees", "وين أدفع رسوم الدورة؟", "Where do I pay the course fee?", "الدفع يكون لدى الجهة المنظمة حسب طريقتها الرسمية. مرصاد ما يستقبل أموال أو بيانات بطاقات بنكية.", "Pay through the organizer’s official method. Mirsad does not collect payments or card details.", /ادفع|الدفع|payment|where.*pay/),
  faq("refund", "fees", "شلون ألغي أو أسترجع المبلغ؟", "How do I cancel or request a refund?", "تواصل مع الجهة المنظمة وراجع سياسة الإلغاء والاسترجاع الخاصة بالدورة. ما أقدر أضمن قبول الاسترجاع أو أنفذه من مرصاد.", "Contact the organizer and check the course cancellation and refund policy. Mirsad cannot guarantee or process refunds.", /استرج|استرد|الغي|الغاء|refund|cancel/),
  faq("discount", "fees", "في خصم للطلبة؟", "Is there a student discount?", "ما نؤكد خصمًا إلا إذا أعلنته الجهة. راجع صفحة التسجيل أو اسأل المنظم عن خصم الطلبة وشروطه.", "Discounts need an official announcement. Check the application page or ask about student discounts and their conditions.", /خصم|discount/),
  faq("extra-fees", "fees", "الرسوم تشمل المواد والشهادة؟", "Does the fee include materials and a certificate?", "التغطية تختلف حسب البرنامج. تحقق من الجهة هل المواد أو الاختبارات أو الشهادة لها رسوم إضافية.", "Inclusions vary. Ask whether materials, exams or certificates have extra charges."),
  faq("certificate", "attendance", "هل أحصل على شهادة معتمدة؟", "Will I get an accredited certificate?", "وجود شهادة أو اعتماد لازم يكون مذكورًا رسميًا. راجع نوع الشهادة، الجهة المانحة، وشروط الحضور والنجاح في صفحة الدورة.", "Certificates and accreditation need official confirmation. Check the issuer, certificate type, attendance and passing requirements.", /شهاده|شهادات|معتمد|certificate|accredit/),
  faq("online", "attendance", "شلون ألقى دورات أونلاين؟", "How do I find online courses?", "اختَر «عن بُعد» من فلتر الحضور، أو اكتب «دورات أونلاين». رابط الدخول يرسله المنظم حسب ترتيباته.", "Choose Online in the attendance filter, or search “online courses.” Joining instructions come from the organizer."),
  faq("recording", "attendance", "هل فيه تسجيل للمحاضرات؟", "Are sessions recorded?", "توفر تسجيل للمحاضرات تحدده الجهة. ما أقدر أؤكده من كون الدورة أونلاين؛ اسأل المنظم قبل التسجيل.", "Recording availability is set by the organizer. An online format does not imply recordings are provided.", /تسجيل للمحاضر|مسجله|recorded|recording/),
  faq("absence", "attendance", "إذا غبت عن يوم شنو يصير؟", "What if I miss a session?", "نسبة الحضور والتعويض وتأثير الغياب على الشهادة تختلف حسب الجهة. راجع شروط الدورة وتواصل مع المنظم.", "Attendance, make-up sessions and certificate rules vary. Check the course terms and contact the organizer.", /غبت|غياب|miss a session|absence/),
  faq("equipment", "attendance", "أحتاج لابتوب أو أدوات؟", "Do I need a laptop or equipment?", "راجع قائمة المتطلبات في الإعلان أو صفحة التسجيل. إذا ما ذُكرت الأدوات، اسأل الجهة قبل الحضور.", "Check the announcement or application requirements. If equipment is not listed, ask the organizer before attending.", /لابتوب|ادوات|laptop|equipment/),
  faq("teaching-language", "attendance", "شنو لغة تقديم الدورة؟", "What language is the course taught in?", "لغة الموقع أو عنوان الدورة ما تثبت لغة التدريس. راجع الوصف الرسمي أو اسأل الجهة إذا مو مذكورة.", "The site or title language does not prove the teaching language. Check the official description or ask the organizer.", /لغه.*دور|لغه التدريس|teaching language|language.*taught/),
  faq("accessibility", "attendance", "المكان مناسب لذوي الإعاقة؟", "Is the venue accessible?", "تواصل مع الجهة للتأكد من التسهيلات المناسبة لاحتياجك؛ ما عندنا بيانات موثّقة عن تجهيزات كل مكان.", "Contact the organizer about accommodations for your needs; we do not have verified accessibility details for every venue.", /اعاقه|احتياجات خاصه|accessible|accessibility/),
  faq("transport", "attendance", "في مواصلات أو مواقف؟", "Are transport or parking provided?", "راجع معلومات المكان عند الجهة أو تواصل معها. ظهور عنوان الدورة لا يعني توفر نقل أو مواقف مجانية.", "Check venue information with the organizer. A listed address does not imply transport or free parking.", /مواصلات|مواقف|parking|transport/),
  faq("search", "directory", "شلون أبحث عن دورة تناسبني؟", "How do I find a suitable course?", "افتح «كل الفرص» واستخدم فلاتر المجال والعمر والجهة والنوع والحضور. راجع شروط القبول في المصدر.", "Open All opportunities and use field, age, organizer, type and attendance filters. Check admission requirements at the source."),
  faq("sources", "directory", "شنو الجهات اللي تتابعونها؟", "Which organizers do you monitor?", "نتابع CODED وKFAS وKGBC وKISR ومركز صباح الأحمد وجهات جامعة الكويت. قسم المصادر يعرض حالة الفحص؛ قد لا تكون للجهة فرص مفتوحة حاليًا.", "We monitor CODED, KFAS, KGBC, KISR, SACGC and Kuwait University providers. Sources shows check status; an organizer may have no current openings.", /شنو الجهات|اي جهات|مصادر|من وين.*دورات|which organizers/),
  faq("updates", "directory", "متى يتحدث دليل الدورات؟", "How often is the directory updated?", "الفحص مجدول كل نصف ساعة وقد يتأخر. وقت آخر فحص وحالة كل جهة ظاهر في قسم المصادر؛ راجع المصدر الرسمي عند التسجيل.", "Checks are scheduled every 30 minutes and can be delayed. Sources shows the last check and status; verify details at registration.", /يتحدث|تحديث الدليل|how often|updated/),
  faq("missing", "directory", "ليش ما تطلع دورات لجهة معينة؟", "Why does an organizer have no courses listed?", "قد ما عندها تسجيل مفتوح، أو الإعلان ناقص معلومات، أو الفحص ما اكتمل. راجع حالة الجهة في المصادر؛ خلو الدليل ما يثبت عدم وجود دورات لديها.", "Registration may be closed, details incomplete, or a source check unfinished. An empty directory does not prove the organizer has no courses.", /ليش.*(?:ما تطلع|مافي|ما في|ما تظهر)|no courses listed/),
  faq("expired", "directory", "ليش اختفت دورة من الموقع؟", "Why did a course disappear?", "قد انتهى التسجيل أو بدأت الدورة، أو تغيّرت معلومات المصدر وتعذّر تأكيدها. افتح موقع الجهة للتأكد من الوضع الحالي.", "Registration may have closed, the course may have started, or changed source information could not be verified. Check the organizer’s site.", /اختفت|اختفي|disappear/),
  faq("unknown", "directory", "شنو يعني غير معلن من الجهة؟", "What does not announced by the organizer mean?", "المعلومة غير موجودة في المصدر المتوفر، لذلك ما نخمنها. راجع الجهة قبل اتخاذ قرار يعتمد عليها.", "That fact is absent from the available source, so we do not guess it. Confirm with the organizer before relying on it."),
  faq("best", "directory", "شلون تختارون الأبرز؟", "How are featured courses selected?", "الأبرز فرص مختارة من الإعلانات، و«يغلق قريبًا» ترتيب حسب نهاية التسجيل. العرض ما يعتبر ضمان جودة أو ترتيبًا للشعبية.", "Featured listings are selected announcements; closing-soon listings use registration deadlines. Neither guarantees quality or popularity.", /شلون.*الابرز|كيف.*الابرز|featured/),
  faq("bot", "help", "شنو يقدر يسوي بوت مرصاد؟", "What can Mirsad Bot do?", "أعرض إجابات محفوظة للأسئلة التي تختارها عن التسجيل والشروط واستخدام الموقع. ما فيه كتابة حرة أو ذكاء اصطناعي. تفاصيل كل دورة في بطاقتها ومصدرها الرسمي.", "I show saved answers to the questions you select about registration, requirements and the site. There is no free typing or AI. Find course-specific details on the card and official source.", /من انت|شنو مرصاد|ما هو مرصاد|شنو تقدر|who are you|what can.*bot/),
  faq("broken-link", "help", "رابط التسجيل ما يفتح، شسوي؟", "What if the registration link does not open?", "جرّب فتح المصدر الرسمي من بطاقة الدورة وتحديث الصفحة. إذا المشكلة مستمرة تواصل مع الجهة؛ لا ترسل بياناتك لرابط بديل غير موثوق.", "Try the official source link on the card and refresh. If it still fails, contact the organizer; do not submit details through unverified replacement links.", /رابط.*(?:ما يفتح|خربان|مو شغال)|link.*(?:broken|not open)/),
  faq("load", "help", "الدورات ما تتحمل عندي؟", "What if courses do not load?", "تأكد من الإنترنت وحدّث الصفحة، وراجع حالة المصادر. إذا الاتصال متعذّر فهذا مو دليل على عدم وجود دورات. أسئلة استخدام الموقع تعمل حتى أثناء تعذّر الدليل.", "Check your connection, refresh and review Sources. A connection failure does not mean there are no courses. Site-help questions still work.", /ما تتحمل|ما تحمل|not load/),
  faq("privacy", "help", "أرسل لكم بياناتي الشخصية؟", "Should I send personal details here?", "لا ترسل رقمك المدني أو معلومات الدفع أو كلمات المرور للبوت. التسجيل يتم لدى الجهة. المحادثة الحالية في ذاكرة الصفحة وتختفي عند إعادة تحميلها.", "Do not send civil IDs, payment information or passwords to the bot. Register with the organizer. This conversation stays in page memory and clears on reload.", /بياناتي|خصوصيه|privacy|personal details/),
  faq("language", "help", "شلون أغيّر لغة الموقع؟", "How do I change the site language?", "اضغط EN / عربي أعلى الصفحة. لغة البوت تتبع اختيارك؛ تفاصيل الإعلان قد تبقى بلغة الجهة الرسمية.", "Use EN / عربي at the top. The bot follows your choice; announcement details may remain in the organizer’s language.", /اغير.*لغه|change.*language/),
  faq("theme", "help", "شلون أفعّل الوضع الداكن؟", "How do I enable dark mode?", "اضغط زر الشمس أو القمر أعلى الصفحة لتبديل النمط. يحفظ الموقع اختيارك على جهازك.", "Use the sun or moon button at the top. Your theme preference is saved on this device.", /الوضع الداكن|dark mode|light mode/),
  faq("reset", "help", "شلون أبدأ بحث جديد؟", "How do I start a new search?", "أغلق البوت وافتح «كل الفرص»، ثم اضغط «مسح الكل» لإزالة الفلاتر وابدأ بحثك الجديد.", "Close the bot, open All opportunities and choose Clear all to reset the filters."),
];

export function answerMirsad(question: string, catalog: LearningOpportunity[], language: "ar" | "en", previous: BotContext = {}, available = true, faqId?: string) {
  const q = normalize(question);
  const t = (ar: string, en: string) => language === "ar" ? ar : en;
  const reset = /من جديد|كل الدورات|كل الفرص|reset|all courses/.test(q);
  const continuing = /^(?:و(?=مجاني|حضوري|اونلاين|للعمر)|نفس|بس |فقط |also |only )/.test(q);
  const context: BotContext = reset || !continuing ? { ids: previous.ids } : { ...previous };
  const result = (reply: string, rows: LearningOpportunity[] = []) => ({ reply, rows, context });
  const help = botFaqs.find(item => item.id === faqId) ?? botFaqs.find(item => normalize(item.ar) === q || normalize(item.en) === q) ?? botFaqs.find(item => item.aliases?.test(q));
  if (help) return { reply: language === "ar" ? help.answerAr : help.answerEn, rows: [], context: previous, matchedFaq: help.id };
  if (/^(هلا|هلا والله|مرحبا|السلام عليكم|اهلا|hi|hello|hey)$/.test(q)) return result(t("هلا فيك! أنا بوت مرصاد. اسألني عن الدورات، العمر، الرسوم، المواعيد، المكان أو التسجيل. تقدر تقول: عمري 16 وأبي ورشة تقنية.", "Hello! I’m Mirsad Bot. Ask about courses, ages, fees, dates, locations or registration. Try: I’m 16 and want a technology workshop."));
  if (/^(شكرا|مشكور|يعطيك العافيه|thanks|thank you)$/.test(q)) return result(t("العفو! شنو تحب تعرف بعد؟", "You’re welcome! What else would you like to know?"));
  if (/تغير.*لغه|انجليزي|english|change language/.test(q) && !/دور|course/.test(q)) return result(t("غيّر لغة الموقع من زر EN / عربي أعلى الصفحة. البوت يتبع اللغة اللي تختارها.", "Use EN / عربي at the top of the page. The bot follows your selected language."));
  if (/داكن|فاتح|dark|light mode/.test(q)) return result(t("زر الشمس أو القمر أعلى الصفحة يغيّر النمط، ويحفظ اختيارك على جهازك.", "Use the sun or moon button at the top. Your preference is saved on this device."));
  if (/تحديث|يتحدث|البوت يشتغل|update|how often/.test(q)) return result(t("البوت مجدول لفحص المصادر كل نصف ساعة وقد يتأخر التشغيل. شوف وقت آخر فحص وحالة كل جهة في قسم المصادر. الفرص المنتهية تختفي من النتائج.", "Source checks are scheduled every 30 minutes and can be delayed. See Sources for each organizer’s last check and status. Expired opportunities are hidden."));
  if (/^(?:من انت|شنو مرصاد|ما هو مرصاد|هل انت ذكاء اصطناعي|who are you|are you ai|what is mirsad)$/.test(q)) return result(t("أنا بوت مرصاد، أبحث في بيانات الدورات وأجاوب عن استخدام الموقع بقواعد جاهزة، بدون خدمة AI. ما عندي إجابات موثوقة لكل الأسئلة العامة.", "I’m Mirsad Bot: a rule-based course finder and site guide, with no AI service. I don’t have reliable answers to every general question."));
  if (/استرجاع|استرداد|الغاء|refund|cancel/.test(q)) return result(t("التسجيل والدفع والإلغاء عند الجهة المنظمة. راجع سياسة الاسترجاع في موقعها وتواصل معها؛ مرصاد ما يستقبل دفعات أو يغيّر التسجيلات.", "Registration, payments and cancellations are handled by the organizer. Check their refund policy and contact them; Mirsad does not take payments or change bookings."));
  if (/شهاده|معتمد|certificate|accredit/.test(q)) return result(t("ما أقدر أؤكد شهادة أو اعتماد إلا إذا ذكرته الجهة رسميًا. افتح تفاصيل الدورة ثم المصدر الرسمي وتحقق من نوع الشهادة وشروط الحصول عليها.", "A certificate or accreditation is only confirmed by the organizer. Open the course details and official source to check the certificate and its requirements."));
  if (/مقاعد|مضمون|قبول|seats|acceptance|guarantee/.test(q)) return result(t("عرض الدورة أو وجود رابط التسجيل ما يضمن مقعد أو قبول. توفر المقاعد وشروط القبول تتأكد منها في صفحة التسجيل الرسمية.", "A course listing or application link does not guarantee a seat or acceptance. Check availability and admission requirements on the official registration page."));
  if (/كيف.*سجل|شلون.*سجل|طريقه التسجيل|how.*register|how.*apply/.test(q)) return result(t("افتح بطاقة الدورة، ثم اضغط «موقع الجهة للتسجيل». يكمل التسجيل في الموقع الرسمي للجهة. ما تحتاج حساب في مرصاد لتصفح الدورات.", "Open a course card, then choose Official registration. Complete your application on the organizer’s website. You don’t need a Mirsad account to browse."));
  if (/مصادر|الجهات|من وين|sources|organizers/.test(q)) return result(t("نتابع مواقع CODED وKFAS وKGBC وKISR ومركز صباح الأحمد وجهات جامعة الكويت. قسم المصادر يوضح حالة الفحص؛ وجود جهة ما يعني أن عندها تسجيل مفتوح حاليًا.", "We monitor official sites for CODED, KFAS, KGBC, KISR, SACGC and Kuwait University providers. Sources shows check status; an organizer may have no current registration."));

  const age = q.match(/(?:عمري|عمره|عمرها|عمر|age|aged|i am|im)\s*(\d{1,3})\b/) ?? q.match(/\b(\d{1,3})\s*(?:سنه|سنوات|years?)/);
  if (age) context.age = Number(age[1]);
  const organizers: [RegExp, string][] = [[/kfas|كفاس|التقدم العلمي/, "KFAS"], [/coded|كودد/, "CODED"], [/kgbc|المباني الخضراء/, "KGBC"], [/kisr|الابحاث العلميه/, "KISR"], [/sacgc|صباح الاحمد/, "SACGC"], [/جامعه الكويت|kuwait university/, "جامعة الكويت"]];
  const fields: [RegExp, string][] = [[/تقني|برمج|روبوت|ذكاء|technology|coding|robot|\bai\b|programming/, "التقنية والذكاء الاصطناعي"], [/هندس|طاقه|engineer|energy/, "الهندسة والطاقة"], [/صحه|اسعاف|سلامه|health|safety/, "الصحة والسلامة"], [/فن|تصميم|ابداع|design|\bart\b/, "الفنون والإبداع"], [/مهار|ادار|اعمال|skill|business|management/, "الأعمال والمهارات"]];
  const org = organizers.find(([pattern]) => pattern.test(q));
  const field = fields.find(([pattern]) => pattern.test(q));
  if (org) context.organizer = org[1];
  if (field) context.field = field[1];
  if (/ورشه|ورش|workshop/.test(q)) context.kind = "workshop";
  else if (/معسكر|bootcamp/.test(q)) context.kind = "camp";
  else if (!reset && /دوره|دورات|course/.test(q)) context.kind = "course";
  if (/اونلاين|عن بعد|online|remote/.test(q)) context.mode = "online";
  if (/حضوري|in person/.test(q)) context.mode = "in_person";
  if (/مجاني|بلاش|free/.test(q)) context.free = true;
  const detail = /سعر|رسوم|بكم|(?:^| )جم(?: |$)|how much|price|cost|fee|مده|كم يوم|duration|how long|مكان|وين|where|location|متي|موعد|تاريخ|when|date|deadline|عمر|age|وصف|تفاصيل|about|details|سجل|register|apply/.test(q);
  const explicit = catalog.filter(item => [item.title, item.titleEn].some(title => title && normalize(title).length > 4 && q.includes(normalize(title))));
  const followup = detail && !age && !org && !field && !/ورشه|دوره|دورات|workshop|course|مجاني|free/.test(q) && previous.ids?.length;
  let rows = explicit.length ? explicit : followup ? catalog.filter(item => previous.ids?.includes(item.id)) : catalog.filter(item =>
    (!context.organizer || item.organizer.includes(context.organizer)) && (!context.field || item.category === context.field)
    && (!context.kind || item.kind === context.kind) && (!context.mode || item.mode === context.mode)
    && (!context.free || item.priceKwd === 0)
    && (context.age === undefined || ((item.minAge !== null || item.maxAge !== null) && (item.minAge === null || context.age >= item.minAge) && (item.maxAge === null || context.age <= item.maxAge))));
  // Unknown subjects must not silently turn into an unfiltered course list.
  if (!explicit.length && !followup && !org && !field && !detail && !reset) {
    const stop = new Set(normalize("ابي ابغي اريد وابي عندكم عندك هل في فيه عن لي من لو سمحت ابحث اقترح رشح ورشة ورش دورة دورات معسكر فرص مجانية مجاني متاح متاحة حضوري اونلاين بعد كلها شنو ايش دوراتكم course courses workshop workshops bootcamp find show me a an the any available free online remote in person please want i to").split(" "));
    const terms = q.split(" ").filter(word => word.length > 2 && !stop.has(word) && !/^\d+$/.test(word));
    if (terms.length) rows = rows.filter(item => { const haystack = normalize([item.title, item.titleEn, item.description, item.subcategory, ...(item.tags ?? [])].join(" ")); return terms.every(term => haystack.includes(term)); });
  }
  if (!available) return result(t("بيانات الدورات غير متاحة حاليًا. جرّب تحديث الصفحة، أو اسألني عن التسجيل وطريقة استخدام الموقع.", "Course data is currently unavailable. Refresh the page, or ask about registration and how to use the site."));
  const known = explicit.length || followup || age || org || field || /دور|ورش|معسكر|فرص|اقترح|رشح|ابحث|عندكم|متاح|course|workshop|bootcamp|find|recommend|available|free|مجاني|حضوري|online|كل الفرص/.test(q);
  if (!known) return result(detail ? t("أي دورة تقصد؟ اكتب اسمها كما يظهر في الدليل، أو اطلب دورات في مجال معين أولًا.", "Which course do you mean? Enter its title from the directory, or search a field first.") : t("ما عندي جواب موثوق لهذا السؤال. أقدر أساعدك بالدورات والعمر والرسوم والمواعيد والتسجيل واستخدام مرصاد. اكتب مثلًا: ورش مجانية، دورات KISR، أو شلون أسجل؟", "I don’t have a reliable answer to that question. I can help with courses, ages, fees, dates, registration and Mirsad. Try: free workshops, KISR courses, or how do I register?"));
  rows = rows.slice(0, 5);
  context.ids = rows.map(item => item.id);
  if (!rows.length) return result(t("ما لقيت فرص مطابقة في الدليل الحالي. جرّب «كل الفرص» لبدء بحث جديد. إذا حددت عمرًا، نستبعد الدورات اللي ما أعلنت أعمارها؛ هذا ما يعني عدم وجود دورات لدى الجهات.", "No matching opportunities in the current directory. Try “all courses” to reset. Age searches exclude unpublished age ranges; this does not mean organizers have no courses."));
  const unknown = t("غير معلن من الجهة", "Not announced by the organizer");
  const descriptions = rows.map(item => {
    const title = language === "en" ? item.titleEn || item.title : item.title;
    const facts: string[] = [];
    if (/سعر|رسوم|بكم|(?:^| )جم(?: |$)|how much|price|cost|fee|مجاني|free/.test(q)) facts.push(t("الرسوم: ", "Fees: ") + (item.priceKwd === null ? unknown : item.priceKwd === 0 ? t("مجاني", "Free") : `${item.priceKwd} KWD`));
    if (/مده|كم يوم|duration|how long/.test(q)) facts.push(t("المدة: ", "Duration: ") + (item.duration || unknown));
    if (/مكان|وين|where|location/.test(q)) facts.push(t("المكان: ", "Location: ") + item.location);
    if (/متي|موعد|تاريخ|when|date|deadline/.test(q)) facts.push(t("الموعد: ", "Schedule: ") + item.schedule, t("إغلاق التسجيل: ", "Registration closes: ") + (item.registrationEndsAt ? new Date(item.registrationEndsAt).toLocaleString(language === "ar" ? "ar-KW" : "en-KW", { timeZone: "Asia/Kuwait" }) : unknown));
    if (/عمر|age/.test(q)) facts.push(t("العمر: ", "Age: ") + (item.minAge === null && item.maxAge === null ? unknown : `${item.minAge ?? "…"}–${item.maxAge ?? "…"}`));
    if (/وصف|تفاصيل|about|details/.test(q)) facts.push(item.description);
    return title + (facts.length ? "\n" + facts.join("\n") : " — " + item.organizer);
  });
  return result(descriptions.join("\n\n") + "\n\n" + t("اضغط بطاقة الدورة للتفاصيل والتسجيل الرسمي. تقدر تسأل بعدها: بكم؟ وين؟ متى؟", "Open a course card for details and official registration. You can follow up with: how much, where, or when?"), rows);
}
